name: MDS_testing_v2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - altair=5.3.0
  - beautifulsoup4=4.12.3
  - cartopy=0.23.0
  - dash=2.17.1
  - matplotlib=3.8.4
  - numpy=1.26.4
  - obspy=1.4.1
  - pandas=2.2.2
  - pillow=10.4.0
  - plotly=5.22.0
  - pyyaml=6.0.1
  - requests=2.32.3
  - streamlit=1.37.0
  - tqdm=4.66.4
  - pip
  - WeasyPrint
  - pygithub
  - pip:
      - torch
      - seisbench

